### ISSUE TITLE
No section name mongo

### ISSUE THREAD

**Issue by Falcone8** [athphane/userbot#50]
File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/root/userbot/userbot/__init__.py", line 45, in <module>
    MONGO_URL = config.get("mongo", "url")
  File "/usr/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.9/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'mongo'
![Immagine 2021-06-09 100336](https://user-images.githubusercontent.com/71499553/121316831-0115e480-c90a-11eb-9442-6f2597b71f6b.png)

**Comment by athphane** [comment]
Refer to [userbot.ini.sample](https://github.com/athphane/userbot/blob/master/userbot.ini.sample) for required variables in the `userbot.ini` file

**Comment by Falcone8** [comment]
Ok thanks

**Comment by Falcone8** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/ubuntu/Clienti/@mydripistalen/Pyrogram-Userbot/userbot/__init__.py", line 45, in <module>
    MONGO_URL = config.get("mongo", "url")
  File "/usr/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.9/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'mongo'

I'm using mongodb atlas

**Comment by Falcone8** [comment]
What i do to fix?

**Comment by athphane** [comment]
Pls check userbot.ini.sample file and make sure you have sections set up properly.

**Comment by Falcone8** [comment]
I setup properly the userbot.ini.sample but i don't resolve my problem

**Comment by Falcone8** [comment]
![image](https://user-images.githubusercontent.com/71499553/125208721-8fc4ab00-e294-11eb-9ae7-6d84548ca408.png)

**Comment by Falcone8** [comment]
@athphane 
Pls help me

**Comment by athphane** [comment]
Ok so the main issue is you have a bunch of unnecessary things in the url value. You only need everything starting from “mongodb+Srv” to “myFirstDatabase”.

**Comment by Falcone8** [comment]
Stesso errore

**Comment by Falcone8** [comment]
Same error

**Comment by Falcone8** [comment]
![image](https://user-images.githubusercontent.com/71499553/125208841-3f018200-e295-11eb-8ed4-56139af4cd91.png)

**Comment by Falcone8** [comment]
I don't know in any way how to fix

**Comment by athphane** [comment]
Are you editing userbot.ini.sample directly? Don't you have a userbot.ini file?

https://github.com/athphane/userbot/issues/50#issuecomment-857487553

**Comment by Falcone8** [comment]
I edited the userbot.ini.sample file and finally turned it into userbot.ini

**Comment by Falcone8** [comment]
@phoenixatom do you know the fix?

**Comment by athphane** [comment]
the error clearly states that the section is missing. Therefore it is not in your userbot.ini file. 

Steps
1- copy userbot.ini.sample to userbot.ini
2- fill in all the values
3- make sure all the sections are there. 
4- run

I know the code in my repository works fine when you have the userbot.ini file. I also now notice that you’re asking for help regarding your fork. I know it’s the same code but since yours is modified I cannot confirm that it will work exactly how I have described. 

Please ask further questions that are directly related to this repository.

**Comment by Falcone8** [comment]
Oh thank you very much

**Comment by Falcone8** [comment]
I resolved the issues thank you so much and excuse me
