### ISSUE TITLE
Summoned.py is giving errors and making bot timeout.

### ISSUE THREAD

**Issue by azuwlaa** [athphane/userbot#51]
![photo_2021-06-20_19-12-23](https://user-images.githubusercontent.com/64716619/122685799-261e2780-d227-11eb-921d-754a15e26666.jpg)

**Comment by athphane** [comment]
You probably don't have MongoDB credentials in your userbot.ini file..

**Comment by athphane** [comment]
Is your MongoDB service running? First time I'm seeing a "Refuse to connect"

**Comment by phoenixatom** [comment]
@athphane
